server:
  port: 8181

spring:
  application:
    name: shopping-center
  profiles:
    active: dev
  cloud:
    consul:
      host: 192.168.0.20
      port: 8500
      #注册到consul的服务名称
      discovery:
        service-name: shopping-center



